#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# TODO: assuming we can scp backups to a backup container
execute "send data to backup container" do
  command "tar -C / -czf - /data/var/db/unfs | ssh -o StrictHostKeyChecking=no #{payload[:backup][:local_ip]} 'cat > /data/var/db/unfs/#{payload[:backup][:backup_id]}.tgz'"
end
