#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

if payload[:member][:type] == 'default'
  # Import rpcbind service (and start)
  directory '/etc/service/rpcbind' do
    recursive true
  end

  template '/etc/service/rpcbind/run' do
    mode 0755
    source 'run-root.erb'
    variables ({ exec: "rpcbind -f" })
  end

  # Import storage service (and start)
  directory '/etc/service/storage' do
    recursive true
  end

  directory '/etc/service/storage/log' do
    recursive true
  end

  template '/etc/service/storage/log/run' do
    mode 0755
    source 'log-run.erb'
    variables ({ svc: "storage" })
  end

  template '/etc/service/storage/run' do
    mode 0755
    variables ({ exec: "/data/sbin/unfsd -d 2>&1" })
  end

  service 'storage' do
    action :enable
    init :runit
  end

  ensure_socket 'storage' do
    port '2049'
    action :listening
  end
end