#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Import rpcbind service (and start)
directory '/etc/service/rpcbind' do
  recursive true
end

template '/etc/service/rpcbind/run' do
  mode 0755
  source 'run-root.erb'
  variables ({ exec: "rpcbind -f" })
end

# Import storage service (and start)
directory '/etc/service/storage' do
  recursive true
end

directory '/etc/service/storage/log' do
  recursive true
end

template '/etc/service/storage/log/run' do
  mode 0755
  source 'log-run.erb'
  variables ({ svc: "storage" })
end

template '/etc/service/storage/run' do
  mode 0755
  variables ({ exec: "/data/sbin/unfsd -d 2>&1" })
end

service 'storage' do
  action :enable
  init :runit
end

ensure_socket 'storage' do
  port '2049'
  action :listening
end

directory '/etc/service/ssh' do
  recursive true
end

directory '/etc/service/ssh/log' do
  recursive true
end

template '/etc/service/ssh/log/run' do
  mode 0755
  source 'log-run.erb'
  variables ({ svc: "ssh" })
end

template '/etc/service/ssh/run' do
  mode 0755
  source 'run-root.erb'
  variables ({ exec: "/opt/gonano/sbin/sshd -D -e 2>&1" })
end

service 'ssh' do
  action :enable
  init :runit
end

ensure_socket 'ssh' do
  port '22'
  action :listening
end

# Attach the IP if provided
if payload[:ips]
  # set up persistance
  file "/etc/nanoinit.d/eth00" do
    content <<-EOF
#!/bin/bash
case $1 in
  start)
    if [[ ! $(ifconfig) =~ eth0:0 ]]; then
      ifconfig eth0:0 #{payload[:ips][:default]}
      arping -A -c 10 -I eth0 #{payload[:ips][:default]}
    fi
    ;;
  stop)
    if [[ $(ifconfig) =~ eth0:0 ]]; then
      ifconfig eth0:0 down
    fi
    ;;
  *)
    echo "$0 start|stop"
    exit 1
    ;;
esac
EOF
    mode 0755
  end

  # bring up interface
  execute "bring up vip" do
    command <<-EOF
      /etc/nanoinit.d/eth00 start
    EOF
  end
end

if Dir.exist? "/opt/nanobox/cron"
  directory '/etc/service/cron'

  hook_file '/etc/service/cron/run' do
    source 'cron'
    mode 0755
  end

  service 'cron' do
    action :enable
    only_if { File.exist?('/etc/service/cron/run') }
  end
end
