#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'


service 'storage' do
  action :disable
  init :runit
end

service 'rpcbind' do
  action :disable
  init :runit
end

directory '/etc/service/rpcbind' do
  action :delete
end

directory '/etc/service/storage' do
  action :delete
end